services:
  server-stats:
    image: kcn333/server-stats:latest
    container_name: server-stats
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    security_opt:
      - no-new-privileges:true
    environment:
      ALLOWED_CORS_SUFFIX: ${your_domain_suffix_here}